OBJECTIONABLE_TAG_SET = set([
    "shota",
    "shotacon",
    "lolicon",
    "abortion",
    "analphagia",
    "beastiality",
    "cannibalism",
    "coprphagia",
    "eel",
    "forced exposure",
    "guro",
    "incest",
    "inseki",
    "insect",
    "low guro",
    "low bestiality",
    "low incest",
    "low lolicon",
    "low scat",
    "low shotacon",
    "mind control",
    "necrophilia",
    "oppai loli",
    "piercing",
    "piss drinking",
    "rape",
    "scat",
    "snuff",
    "urination"
])

